"use client"
import { useEffect, useState, useRef } from 'react'
export default function OrdersPage(){
  const [orders,setOrders]=useState<any[]>([])
  const [role,setRole]=useState<string>("")
  const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [loading,setLoading]=useState(true)
  const [audioUnlocked,setAudioUnlocked]=useState(false)
  const prevReadyRef = useRef<Set<string>>(new Set());
  const prevPendingRef = useRef<Set<string>>(new Set());
  const prevConfirmRef = useRef<Set<string>>(new Set());
  const audioCtxRef = useRef<any>(null)
  const unlockAudio = ()=>{ try{ const AudioCtx = (window as any).AudioContext || (window as any).webkitAudioContext; if(!AudioCtx) return; if(!audioCtxRef.current) audioCtxRef.current = new AudioCtx(); const ctx = audioCtxRef.current; if(ctx.state==='suspended') ctx.resume().then(()=>setAudioUnlocked(true)).catch(()=>{}); else setAudioUnlocked(true) }catch{} }
  const beepLoud = (type:'ready'|'new'|'confirm'|'cancel'='ready')=>{
    try{
      const AudioCtx = (window as any).AudioContext || (window as any).webkitAudioContext; if(!AudioCtx) return; if(!audioCtxRef.current) audioCtxRef.current = new AudioCtx(); const ctx = audioCtxRef.current; if(ctx.state==='suspended'){ ctx.resume().catch(()=>{}); return }
      if((navigator as any).vibrate){ if(type==='cancel') (navigator as any).vibrate([800,200,800]); else if(type==='confirm') (navigator as any).vibrate([500,100,500]); else if(type==='new') (navigator as any).vibrate([200,100,200]); else (navigator as any).vibrate([400,100,800]) }
      const playTone = (freq:number, start:number, dur:number, vol:number)=>{ const o1 = ctx.createOscillator(); const g = ctx.createGain(); o1.frequency.value = freq; o1.type='square'; o1.connect(g); g.connect(ctx.destination); g.gain.setValueAtTime(0, ctx.currentTime+start); g.gain.linearRampToValueAtTime(vol, ctx.currentTime+start+0.02); g.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime+start+dur); o1.start(ctx.currentTime+start); o1.stop(ctx.currentTime+start+dur) }
      if(type==='cancel'){ playTone(300,0,1.2,1.5); playTone(200,0.5,1.2,1.5) } else if(type==='confirm'){ playTone(1500,0,0.5,1.5); playTone(2000,0.4,0.5,1.5) } else if(type==='new'){ playTone(800,0,0.4,1.0); playTone(1000,0.2,0.4,1.0) } else { playTone(1200,0,0.6,1.2); playTone(1800,0.3,0.6,1.2) }
    }catch{}
  }
  const load = async(f?:string,t?:string, silent=false)=>{ if(!silent) setLoading(true); const p = new URLSearchParams(); if(f) p.set('from', f); if(t) p.set('to', t); if(f||t) p.set('all','1'); const res = await fetch('/api/admin/orders?'+p.toString()); const d = await res.json(); const ords = d.orders||[]; if(role==='WAITER'){ const readyIds = ords.filter((o:any)=> (o.status||'').toLowerCase()==='ready').map((o:any)=> o.id as string); readyIds.forEach((id:string)=>{ if(!prevReadyRef.current.has(id)){ beepLoud('ready'); setTimeout(()=>beepLoud('ready'),1000) } }); prevReadyRef.current = new Set(readyIds); const confirmIds = ords.filter((o:any)=> ['awaiting_confirmation','pending_confirmation','awaiting_waiter','unconfirmed','new_cash'].includes((o.status||'').toLowerCase())).map((o:any)=>o.id as string); confirmIds.forEach((id:string)=>{ if(!prevConfirmRef.current.has(id)){ beepLoud('confirm'); setTimeout(()=>beepLoud('confirm'),800) } }); prevConfirmRef.current = new Set(confirmIds) } if(role==='KITCHEN'){ const pendingIds = ords.filter((o:any)=> ['pending','new'].includes((o.status||'').toLowerCase())).map((o:any)=> o.id as string); if(pendingIds.filter((id:string)=>!prevPendingRef.current.has(id)).length>0) beepLoud('new'); prevPendingRef.current = new Set(pendingIds) } setOrders(ords); if(!silent) setLoading(false) }
  useEffect(()=>{ fetch('/api/admin/me').then(r=>r.json()).then(d=> setRole(d.role||'WAITER')); const h=()=>unlockAudio(); document.addEventListener('click',h); document.addEventListener('touchstart',h); return()=>{ document.removeEventListener('click',h); document.removeEventListener('touchstart',h)} },[])
  useEffect(()=>{ if(!role) return; load(); const iv=setInterval(()=>load(from,to,true),3000); return()=>clearInterval(iv)},[role])
  const toNum=(v:any)=>Number(v||0)
  const updateStatus=async(id:string,status:string)=>{ await fetch(`/api/admin/orders/${id}`,{method:'PATCH', headers:{'Content-Type':'application/json'}, body: JSON.stringify({status})}); setOrders(prev=> prev.map(o=> o.id===id? {...o, status} : o)) }
  const confirmCashPos=async(id:string)=>{ await fetch(`/api/admin/orders/${id}`,{method:'PATCH', headers:{'Content-Type':'application/json'}, body: JSON.stringify({status:'pending'})}); await load() }
  const cancelOrder=async(id:string, isOnlinePaid:boolean=false)=>{ const reason=prompt(isOnlinePaid?"STORNO ONLINE - automatski refund! Razlog:":"STORNO - razlog (gost krivo narucio):"); if(reason===null) return; if(!confirm(isOnlinePaid?`Sigurno stornirati i REFUNDIRATI € gostu?\nRazlog: ${reason}`:`Sigurno stornirati?\nRazlog: ${reason||'bez razloga'}`)) return; const res=await fetch(`/api/admin/orders/${id}`,{method:'PATCH', headers:{'Content-Type':'application/json'}, body: JSON.stringify({status:'cancelled', cancelReason: reason})}); const data=await res.json(); if(!res.ok){ alert("Greška: "+(data.error||"nepoznato")); return } if(data.order?.refundStatus?.startsWith("FAILED")){ alert("Stornirano, ali REFUND NIJE USPIO: "+data.order.refundStatus+"\nRefindiraj rucno u Stripe dashboardu!") } else if(isOnlinePaid){ alert("Stornirano + REFUND uspješno! € vraćen gostu.") } beepLoud('cancel'); await load() }
  const payMethodLabel=(m:string)=>{ const s=(m||'').toUpperCase(); if(s.includes('CASH')) return 'Gotovina'; if(s.includes('TERMINAL')||s.includes('POS')) return 'POS'; if(s.includes('ONLINE')||s.includes('STRIPE')||s.includes('CARD')) return 'Online'; return m||'Nepoznato' }
  const isOnlinePaid=(o:any)=>{ const m=(o.paymentMethod||'').toUpperCase(); const isOn=m.includes('ONLINE')||m.includes('STRIPE')||m.includes('CARD'); return isOn && (o.paymentStatus||'').toUpperCase()==='PAID' }
  if(role==='RESTAURANT_ADMIN' || role==='SUPER_ADMIN'){
    const active=orders.filter((o:any)=> o.status!=='cancelled'); const total=active.reduce((s,o)=> s+toNum(o.total),0)
    return (<main className="max-w-7xl mx-auto p-4"><h1 className="text-xl font-bold mb-3">Narudžbe</h1><div className="bg-white border rounded-xl p-3 mb-3 flex gap-2"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="border rounded-lg px-3 h-8 text-sm"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="border rounded-lg px-3 h-8 text-sm"/><button onClick={()=>load(from,to)} className="bg-black text-white px-4 h-8 rounded-full text-xs">Filtriraj</button><button onClick={()=>{setFrom('');setTo('');load()}} className="border px-4 h-8 rounded-full text-xs">Reset</button></div><div className="bg-white border rounded-xl overflow-hidden"><div className="overflow-auto max-h-"><table className="w-full text-xs"><thead className="bg-zinc-50 text-left text- text-neutral-500 sticky top-0"><tr><th className="p-2">Vrijeme</th><th className="p-2">Stol</th><th className="p-2">Status</th><th className="p-2">Plaćanje</th><th className="p-2">Iznos</th><th className="p-2">Razlog storna</th><th className="p-2">Akcija</th></tr></thead><tbody>{orders.map((o:any)=>{ const cancelled=o.status==='cancelled'; return (<tr key={o.id} className={`border-t ${cancelled?'bg-red-50':''}`}><td className="p-2">{new Date(o.createdAt).toLocaleTimeString('hr-HR')}</td><td className="p-2 font-bold">#{o.table?.number}</td><td className="p-2"><span className={`px-2 py-0.5 rounded-full text- ${cancelled?'bg-red-600 text-white':'bg-zinc-100'}`}>{o.status} {o.refundStatus?`(${o.refundStatus})`:''}</span></td><td className="p-2">{o.paymentStatus} • {payMethodLabel(o.paymentMethod)} {o.refundId? <span className="bg-green-100 px-1 rounded text-">REFUND</span>:null}</td><td className="p-2 font-bold">€{toNum(o.total).toFixed(2)}</td><td className="p-2 max-w- truncate text-">{o.cancelReason||'-'}</td><td className="p-2">{!cancelled && <button onClick={()=>cancelOrder(o.id, isOnlinePaid(o))} className="bg-red-600 text-white px-2 py-1 rounded-full text-">{isOnlinePaid(o)?'STORNO + REFUND':'STORNO'}</button>}</td></tr>)})}</tbody></table></div></div></main>)
  }
  if(role==='KITCHEN'){
    const pending = orders.filter((o:any)=> ['pending','new'].includes((o.status||'').toLowerCase())); const preparing = orders.filter((o:any)=> ['preparing','in_progress'].includes((o.status||'').toLowerCase())); const ready = orders.filter((o:any)=> ['ready'].includes((o.status||'').toLowerCase()))
    return (<main className="p-3">{!audioUnlocked && <div onClick={unlockAudio} className="bg-red-600 text-white rounded-xl p-3 mb-3 animate-pulse font-black cursor-pointer">🔊 KLIKNI ZA ZVUK</div>}<div className="flex justify-between items-center mb-3"><h1 className="text-lg font-black">Kuhinja - bez storna</h1><button onClick={()=>{unlockAudio(); beepLoud('new')}} className="px-4 h-8 rounded-full text-xs font-bold bg-black text-white">TEST</button></div><div className="flex gap-3 overflow-auto pb-4"><div className="flex-1 min-w-"><div className="p-2 font-bold text-xs uppercase bg-white rounded-t-xl border">Nove ({pending.length})</div><div className="space-y-2 p-2 bg-zinc-50 rounded-b-xl min-h- border border-t-0">{pending.map((o:any)=> (<div key={o.id} className="bg-white border rounded-xl p-3"><div className="flex justify-between mb-2"><div className="text-2xl font-black">Stol {o.table?.number}</div><div className="text-xs px-2 py-1 rounded-full bg-zinc-100">{Math.floor((Date.now() - new Date(o.createdAt).getTime())/60000)} min</div></div><div className="space-y-1">{o.items?.map((i:any)=>(<div key={i.id} className="text-sm"><span className="font-black">{i.quantity}x </span>{i.menuItem?.name}</div>))}</div><button onClick={()=>updateStatus(o.id,'preparing')} className="mt-3 w-full bg-black text-white h-10 rounded-xl text-sm font-bold">KRENI</button></div>))}</div></div><div className="flex-1 min-w-"><div className="p-2 font-bold text-xs uppercase bg-orange-50 rounded-t-xl border border-orange-200">U pripremi ({preparing.length})</div><div className="space-y-2 p-2 bg-zinc-50 rounded-b-xl min-h- border border-t-0">{preparing.map((o:any)=> (<div key={o.id} className="bg-white border rounded-xl p-3"><div className="text-2xl font-black">Stol {o.table?.number}</div><div className="space-y-1 mt-2">{o.items?.map((i:any)=>(<div key={i.id} className="text-sm"><span className="font-black">{i.quantity}x </span>{i.menuItem?.name}</div>))}</div><button onClick={()=>updateStatus(o.id,'ready')} className="mt-3 w-full bg-green-600 text-white h-12 rounded-xl text-base font-black">SPREMNO 🔔</button></div>))}</div></div><div className="flex-1 min-w-"><div className="p-2 font-bold text-xs uppercase bg-green-50 rounded-t-xl border border-green-200">Spremne ({ready.length})</div><div className="space-y-2 p-2 bg-zinc-50 rounded-b-xl min-h- border border-t-0">{ready.map((o:any)=> (<div key={o.id} className="bg-white border rounded-xl p-3 border-green-300"><div className="text-2xl font-black">Stol {o.table?.number}</div><div className="space-y-1 mt-2">{o.items?.map((i:any)=>(<div key={i.id} className="text-sm"><span className="font-black">{i.quantity}x </span>{i.menuItem?.name}</div>))}</div><div className="mt-3 w-full bg-green-50 border border-green-200 text-green-800 h-10 rounded-xl text-xs font-bold flex items-center justify-center">Čeka konobara</div></div>))}</div></div></div></main>)
  }
  const awaitingConfirm = orders.filter((o:any)=> ['awaiting_confirmation','pending_confirmation','awaiting_waiter','unconfirmed','new_cash'].includes((o.status||'').toLowerCase()))
  const activeOrders = orders.filter((o:any)=>!['awaiting_confirmation','pending_confirmation','awaiting_waiter','unconfirmed','new_cash','cancelled'].includes((o.status||'').toLowerCase()))
  const readyOrders = orders.filter((o:any)=> o.status.toLowerCase()==='ready')
  return (<main className="max-w-6xl mx-auto p-3">{!audioUnlocked && <div onClick={unlockAudio} className="bg-red-600 text-white rounded-xl p-3 mb-3 flex items-center justify-between cursor-pointer animate-pulse"><div className="font-black">🔊 KLIKNI ZA ZVUK</div><div className="bg-white text-red-600 px-3 py-1 rounded-full text-xs font-bold">AKTIVIRAJ</div></div>}{awaitingConfirm.length>0 && <div className="bg-orange-500 text-white rounded-xl p-3 mb-4"><div className="font-black text-lg mb-2">⚠️ {awaitingConfirm.length} ČEKA POTVRDU (Gotovina/POS)</div><div className="grid md:grid-cols-2 gap-3">{awaitingConfirm.map((o:any)=> (<div key={o.id} className="bg-white text-black rounded-xl p-3"><div className="flex justify-between mb-2"><div className="text-xl font-black">Stol {o.table?.number} - {payMethodLabel(o.paymentMethod)}</div><div className="text-xs bg-orange-100 px-2 py-1 rounded-full font-bold">€{toNum(o.total).toFixed(2)}</div></div><div className="space-y-1 mb-3 text-sm">{o.items?.map((i:any)=>(<div key={i.id}>{i.quantity}x {i.menuItem?.name}</div>))}</div><div className="flex gap-2"><button onClick={()=>confirmCashPos(o.id)} className="flex-1 bg-black text-white h-12 rounded-xl font-black text-sm">✅ POTVRDI I POŠALJI KUHINJI</button><button onClick={()=>cancelOrder(o.id,false)} className="px-4 bg-red-600 text-white h-12 rounded-xl font-black text-xs">STORNO</button></div></div>))}</div></div>}<div className="flex justify-between items-center mb-3"><h1 className="text-lg font-bold">Konobar {audioUnlocked?'🔊':''}</h1><button onClick={()=>{unlockAudio(); beepLoud('ready')}} className="px-4 h-8 rounded-full text-xs font-bold bg-black text-white">TEST</button></div>{readyOrders.length>0 && <div className="bg-green-600 text-white rounded-xl p-4 mb-3 animate-pulse font-black">🔔 {readyOrders.length} SPREMNO: {readyOrders.map((o:any)=>'Stol '+o.table?.number).join(', ')}</div>}<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">{activeOrders.slice(0,100).map((o:any)=>{ const isReady = o.status.toLowerCase()==='ready'; return (<div key={o.id} className={`bg-white border rounded-xl p-3 ${isReady?'border-green-500 ring-2 ring-green-200 animate-pulse':''}`}><div className="flex justify-between mb-2"><div className="text-xl font-black">Stol {o.table?.number}</div><span className="text- px-2 py-0.5 rounded-full bg-zinc-100">{o.status}</span></div><div className="text-xs text-neutral-500 mb-2">{new Date(o.createdAt).toLocaleTimeString('hr-HR')} • €{toNum(o.total).toFixed(2)}</div><div className="space-y-1 mb-3 text-sm">{o.items?.map((i:any)=>(<div key={i.id}>{i.quantity}x {i.menuItem?.name}</div>))}</div><div className="flex gap-2">{isReady && <button onClick={()=>updateStatus(o.id,'served')} className="flex-1 bg-black text-white h-9 rounded-xl text-xs font-bold">POSLUŽENO</button>}{!isReady && <div className="flex-1 text- text-neutral-500 flex items-center">Kuhinja radi...</div>}</div></div>)})}</div></main>)
}
