"use client"
import { useEffect, useState } from "react"
type Item = { id:string, name:string, price:number, isBoosted:boolean, boostLevel:number, category:{name:string} }
type Rule = { id:string, sourceId:string, targetId:string, strength:number, type:string, autoGenerated:boolean, source:Item, target:Item }
export default function UpsellPage(){
  const [items,setItems]=useState<Item[]>([])
  const [rules,setRules]=useState<Rule[]>([])
  const [sourceId,setSourceId]=useState("")
  const [targetId,setTargetId]=useState("")
  const [strength,setStrength]=useState(1)
  const [type,setType]=useState("COMPLEMENT")
  const [filterSource,setFilterSource]=useState("all")
  const [search,setSearch]=useState("")
  const load=async()=>{
    const [iRes,rRes]=await Promise.all([fetch("/api/admin/menu"), fetch("/api/admin/upsell")])
    const iData=await iRes.json()
    const rData=await rRes.json()
    setItems(iData.items||[])
    setRules(rData.rules||[])
    if(iData.items?.[0]){ setSourceId(iData.items[0].id); setTargetId(iData.items[1]?.id||iData.items[0].id) }
  }
  useEffect(()=>{load()},[])
  const create=async()=>{
    if(!sourceId||!targetId) return alert("Odaberi oba")
    const r=await fetch("/api/admin/upsell",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sourceId,targetId,strength,type})})
    const j=await r.json()
    if(!r.ok) alert(j.error)
    else setRules([...rules,j])
  }
  const del=async(id:string)=>{
    if(!confirm("Obrisati?")) return
    await fetch(`/api/admin/upsell/${id}`,{method:"DELETE"})
    setRules(p=>p.filter(x=>x.id!==id))
  }
  const updateStrength=async(rule:Rule, newStr:number)=>{
    const r=await fetch(`/api/admin/upsell/${rule.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({strength:newStr})})
    const j=await r.json()
    setRules(p=>p.map(x=>x.id===rule.id?j:x))
  }
  const filtered=rules.filter(r=>{
    const matchSource=filterSource==="all"||r.sourceId===filterSource
    const matchSearch=search===""|| r.source.name.toLowerCase().includes(search.toLowerCase())||r.target.name.toLowerCase().includes(search.toLowerCase())
    return matchSource&&matchSearch
  })
  const grouped: Record<string, Rule[]> = {}
  filtered.forEach(r=>{ if(!grouped[r.sourceId]) grouped[r.sourceId]=[]; grouped[r.sourceId].push(r) })
  return(
    <div className="p-6 max-w-6xl mx-auto">
      <h1 className="text-2xl font-bold">Upsell Editor</h1>
      <p className="text-sm text-gray-500 mb-6">Source → Target. score = strength * (boost?2:1) * (boostLevel+1)</p>
      <div className="border rounded-xl p-4 bg-yellow-50 mb-6">
        <h3 className="font-bold mb-3">+ Novo pravilo</h3>
        <div className="grid grid-cols-1 md:grid-cols-5 gap-3">
          <div><label className="text-xs font-bold">KAD NARUČI</label><select value={sourceId} onChange={e=>setSourceId(e.target.value)} className="w-full border rounded px-2 py-2 mt-1">{items.map(it=><option key={it.id} value={it.id}>{it.name}</option>)}</select></div>
          <div className="flex items-center justify-center text-2xl pt-5">→</div>
          <div><label className="text-xs font-bold">PONUDI</label><select value={targetId} onChange={e=>setTargetId(e.target.value)} className="w-full border rounded px-2 py-2 mt-1">{items.map(it=><option key={it.id} value={it.id}>{it.name} {it.isBoosted?`🔥${it.boostLevel}`:""}</option>)}</select></div>
          <div><label className="text-xs font-bold">Strength {strength}</label><input type="range" min="0.1" max="5" step="0.1" value={strength} onChange={e=>setStrength(Number(e.target.value))} className="w-full mt-3"/><div className="flex justify-between text-xs"><span>0.1</span><span>5</span></div></div>
          <div><label className="text-xs font-bold">Tip</label><select value={type} onChange={e=>setType(e.target.value)} className="w-full border rounded px-2 py-2 mt-1"><option value="COMPLEMENT">COMPLEMENT</option><option value="SIDE">SIDE</option><option value="DRINK">DRINK</option><option value="DESSERT">DESSERT</option><option value="UPGRADE">UPGRADE</option></select></div>
        </div>
        <button onClick={create} className="mt-3 bg-black text-white px-6 py-2 rounded">Dodaj pravilo</button>
      </div>
      <div className="flex gap-3 mb-4">
        <input placeholder="Traži..." value={search} onChange={e=>setSearch(e.target.value)} className="border rounded px-3 py-2 w-64"/>
        <select value={filterSource} onChange={e=>setFilterSource(e.target.value)} className="border rounded px-3 py-2"><option value="all">Svi</option>{items.map(it=><option key={it.id} value={it.id}>{it.name}</option>)}</select>
        <span className="text-sm text-gray-500 py-2">{filtered.length} pravila</span>
      </div>
      <div className="space-y-4">
        {Object.entries(grouped).map(([srcId, ruleList])=>{
          const src=ruleList[0].source
          return(
            <div key={srcId} className="border rounded-xl p-4 bg-white">
              <div className="font-bold mb-2 flex gap-2"><span className="bg-black text-white px-2 py-1 rounded text-sm">{src.name}</span><span className="text-xs text-gray-500">→ {ruleList.length}</span></div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {ruleList.map(r=>(
                  <div key={r.id} className="flex items-center gap-2 border rounded-lg px-3 py-2 bg-gray-50">
                    <span className="flex-1 text-sm">{r.target.name} <span className="text-xs text-gray-500">({r.target.price}€)</span></span>
                    <span className="text-xs bg-white border px-2 py-1 rounded">{r.type}</span>
                    <input type="number" step="0.1" value={r.strength} onChange={e=>updateStrength(r, Number(e.target.value))} className="w-14 border rounded px-1 py-1 text-xs"/>
                    <button onClick={()=>del(r.id)} className="text-red-500 text-xs">✕</button>
                  </div>
                ))}
              </div>
            </div>
          )
        })}
        {filtered.length===0 && <p className="text-gray-400 text-center py-10">Nema pravila</p>}
      </div>
    </div>
  )
}
