"use client";
import { useEffect, useState } from "react";
type Cat = { id:string; name:string; order?:number };
type Item = { id:string; name:string; description?:string|null; price:number; categoryId:string; category:{name:string; id?:string}; imageUrl?:string|null; available:boolean; isBoosted:boolean; boostLevel:number; order?:number; };
export default function ItemsPage(){
  const [cats,setCats]=useState<Cat[]>([]); const [items,setItems]=useState<Item[]>([]); const [filter,setFilter]=useState(""); const [catFilter,setCatFilter]=useState("all"); const [saving,setSaving]=useState<string|null>(null); const [newItem,setNewItem]=useState<any>({ name:"", price:"", categoryId:"", description:"", imageUrl:"", isBoosted:false, boostLevel:0, available:true });
  const parsePrice = (v:any)=>{ if(v===null||v===undefined||v==="") return NaN; const s = String(v).replace(",",".").trim(); return parseFloat(s) }
  const load=async()=>{ const [cRes,mRes] = await Promise.all([fetch("/api/admin/categories"), fetch("/api/admin/menu")]); const cData=await cRes.json(); const mData=await mRes.json(); const categories = cData.all || cData.categories || mData.categories || []; // FIX: koristi all da uključi podkategorije setCats(categories); const allItems = mData.items || categories.flatMap((c:any) => (c.items||[]).map((it:any) => ({...it, category: { name: c.name, id: c.id } }))); setItems(allItems); if(categories[0] &&!newItem.categoryId){ setNewItem((p:any)=>({...p, categoryId:categories[0].id })); } }; useEffect(()=>{ load(); },[]);
  const create=async()=>{
    const priceNum = parsePrice(newItem.price)
    if(!newItem.name || isNaN(priceNum) ||!newItem.categoryId){ alert("Ime, cijena (npr 13.50 ili 13,50), kategorija obavezni"); return; }
    setSaving("new");
    const r=await fetch("/api/admin/menu",{ method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({...newItem, price: priceNum }) });
    const j=await r.json();
    if(!r.ok){ alert(j.error||"Greška"); } else { await load(); setNewItem({ name:"", price:"", categoryId:cats[0]?.id||"", description:"", imageUrl:"", isBoosted:false, boostLevel:0, available:true }); }
    setSaving(null);
  };
  const save=async(it:Item)=>{ setSaving(it.id); const priceNum = parsePrice((it as any).price); if(isNaN(priceNum)){ alert("Neispravna cijena"); setSaving(null); return } await fetch(`/api/admin/menu/${it.id}`,{ method:"PATCH", headers:{"Content-Type":"application/json"}, body:JSON.stringify({...it, price: priceNum}) }); setSaving(null); };
  const del=async(id:string)=>{ if(!confirm("Obrisati artikal?")) return; await fetch(`/api/admin/menu/${id}`,{method:"DELETE"}); setItems((p)=>p.filter(x=>x.id!==id)); };
  const filtered=items.filter((i)=>{ const matchName=i.name.toLowerCase().includes(filter.toLowerCase()); const matchCat=catFilter==="all" || i.categoryId===catFilter; return matchName && matchCat; });
  return (<div className="p-4 max-w-7xl mx-auto"><div className="flex justify-between items-center mb-3"><div><h1 className="text-lg font-bold leading-tight">Artikli</h1><p className="text- text-neutral-500">{filtered.length} artikala • upiši 13.50 ili 13,50</p></div><div className="flex gap-2"><input placeholder="Traži..." value={filter} onChange={e=>setFilter(e.target.value)} className="border rounded-full px-3 h-8 text-xs w-40"/><select value={catFilter} onChange={e=>setCatFilter(e.target.value)} className="border rounded-full px-3 h-8 text-xs"><option value="all">Sve kategorije</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div><div className="bg-zinc-50 border rounded-xl p-3 mb-4"><div className="text- font-bold uppercase tracking-wider mb-2">+ Novi artikal</div><div className="grid grid-cols-12 gap-2"><input placeholder="Naziv *" value={newItem.name} onChange={e=>setNewItem({...newItem, name:e.target.value })} className="col-span-5 border rounded-lg px-2 h-8 text-xs"/><input placeholder="€ npr 13.50 *" inputMode="decimal" value={newItem.price} onChange={e=>setNewItem({...newItem, price:e.target.value })} className="col-span-2 border rounded-lg px-2 h-8 text-xs"/><select value={newItem.categoryId} onChange={e=>setNewItem({...newItem, categoryId:e.target.value })} className="col-span-3 border rounded-lg px-2 h-8 text-xs">{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={create} disabled={saving==="new"} className="col-span-2 bg-black text-white h-8 rounded-full text-xs">{saving==="new"?"...":"Dodaj"}</button></div></div><div className="bg-white border rounded-xl overflow-hidden"><div className="grid grid-cols-12 gap-2 px-3 py-2 bg-zinc-50 text- font-bold uppercase tracking-wider text-neutral-500 border-b"><div className="col-span-4">Naziv</div><div className="col-span-2">Cijena €</div><div className="col-span-2">Kategorija</div><div className="col-span-2">Status</div><div className="col-span-2 text-right">Akcija</div></div><div className="divide-y divide-black/[0.04] max-h- overflow-auto">{filtered.map((it)=>{
    const priceStr = (it as any).price!==undefined? String((it as any).price).replace(".",",") : ""
    return (<div key={it.id} className={`grid grid-cols-12 gap-2 px-3 py-2 items-center hover:bg-zinc-50 ${!it.available?"opacity-50":""}`}><div className="col-span-4"><input value={it.name} onChange={e=>setItems(p=>p.map(x=>x.id===it.id?{...x,name:e.target.value}:x))} className="w-full border rounded-lg px-2 h-7 text-xs font-medium"/></div><div className="col-span-2 flex items-center gap-1"><span className="text- text-neutral-400">€</span><input inputMode="decimal" value={(it as any).price} onChange={e=>setItems(p=>p.map(x=>x.id===it.id?{...x,price:e.target.value as any}:x))} className="w-full border rounded-lg px-2 h-7 text-xs"/></div><div className="col-span-2"><select value={it.categoryId} onChange={e=>setItems(p=>p.map(x=>x.id===it.id?{...x,categoryId:e.target.value}:x))} className="w-full border rounded-lg px-2 h-7 text-xs">{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="col-span-2 flex gap-2 items-center"><label className="flex items-center gap-1 text-"><input type="checkbox" checked={it.available} onChange={e=>setItems(p=>p.map(x=>x.id===it.id?{...x,available:e.target.checked}:x))} className="w-3 h-3"/>Dost.</label><label className="flex items-center gap-1 text-"><input type="checkbox" checked={it.isBoosted} onChange={e=>setItems(p=>p.map(x=>x.id===it.id?{...x,isBoosted:e.target.checked}:x))} className="w-3 h-3"/>🔥</label></div><div className="col-span-2 flex gap-1 justify-end"><button onClick={()=>save(it)} disabled={saving===it.id} className="bg-black text-white px-2.5 h-7 rounded-full text-">{saving===it.id?"...":"Spremi"}</button><button onClick={()=>del(it.id)} className="border px-2.5 h-7 rounded-full text- text-red-600">X</button></div></div>)})}</div></div></div>);
}
