import { NextRequest, NextResponse } from "next/server"
import { getCurrentUser, getImpersonateId } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { getRestaurantId } from "@/lib/getRestaurantId"

export async function GET(){
  const user = await getCurrentUser()
  if(!user) return NextResponse.json({error:"Unauthorized"}, {status:401})
  const impId = await getImpersonateId()
  const restaurantId = getRestaurantId(user, impId)
  if(!restaurantId){
    const r = await prisma.restaurant.findFirst()
    if(!r) return NextResponse.json({rules:[]})
    const rules = await prisma.upsellRule.findMany({
      where:{restaurantId: r.id},
      include:{ source:true, target:true }
    })
    return NextResponse.json({rules})
  }
  const rules = await prisma.upsellRule.findMany({
    where:{restaurantId},
    include:{ source:true, target:true },
    orderBy:[{source:{name:"asc"}},{strength:"desc"}]
  })
  return NextResponse.json({rules})
}

export async function POST(req: NextRequest){
  const user = await getCurrentUser()
  if(!user) return NextResponse.json({error:"Unauthorized"}, {status:401})
  const impId = await getImpersonateId()
  let restaurantId = getRestaurantId(user, impId)
  if(!restaurantId){
    const r = await prisma.restaurant.findFirst()
    restaurantId = r?.id
  }
  if(!restaurantId) return NextResponse.json({error:"No restaurant"}, {status:400})
  const { sourceId, targetId, strength, type } = await req.json()
  if(!sourceId ||!targetId) return NextResponse.json({error:"sourceId i targetId obavezni"}, {status:400})
  if(sourceId===targetId) return NextResponse.json({error:"Ne može isti artikal"}, {status:400})

  const [src, tgt] = await Promise.all([
    prisma.menuItem.findFirst({where:{id:sourceId, restaurantId}}),
    prisma.menuItem.findFirst({where:{id:targetId, restaurantId}})
  ])
  if(!src || !tgt) return NextResponse.json({error:"Artikli ne pripadaju tvom restoranu"}, {status:400})

  try{
    const rule = await prisma.upsellRule.create({
      data:{
        restaurantId,
        sourceId,
        targetId,
        strength: strength? Number(strength) : 1,
        type: type || "COMPLEMENT",
        autoGenerated: false
      },
      include:{ source:true, target:true }
    })
    return NextResponse.json(rule)
  }catch(e:any){
    console.error("upsell create error", e)
    if(e.code==="P2002") return NextResponse.json({error:"Pravilo već postoji za ovu kombinaciju"}, {status:400})
    return NextResponse.json({error:e.message||"Greška"}, {status:500})
  }
}
