import { NextRequest, NextResponse } from "next/server"
import { getCurrentUser } from "@/lib/auth"
import { prisma } from "@/lib/prisma"

export async function GET(){
  const user = await getCurrentUser()
  let restaurantId = user?.restaurantId
  if(!restaurantId){
    const r = await prisma.restaurant.findFirst()
    restaurantId = r?.id
  }
  if(!restaurantId) return NextResponse.json({rules:[]})
  const rules = await prisma.upsellRule.findMany({
    where:{restaurantId},
    include:{ source:true, target:true },
    orderBy:[{source:{name:"asc"}},{strength:"desc"}]
  })
  return NextResponse.json({rules})
}

export async function POST(req: NextRequest){
  const user = await getCurrentUser()
  let restaurantId = user?.restaurantId
  if(!restaurantId){
    const r = await prisma.restaurant.findFirst()
    restaurantId = r?.id
  }
  if(!restaurantId) return NextResponse.json({error:"No restaurant"}, {status:400})
  const { sourceId, targetId, strength, type } = await req.json()
  if(!sourceId ||!targetId) return NextResponse.json({error:"sourceId i targetId obavezni"}, {status:400})
  if(sourceId===targetId) return NextResponse.json({error:"Ne može isti artikal"}, {status:400})
  try{
    const rule = await prisma.upsellRule.create({
      data:{
        restaurantId,
        sourceId,
        targetId,
        strength: strength? Number(strength) : 1,
        type: type || "COMPLEMENT",
        autoGenerated: false
      },
      include:{ source:true, target:true }
    })
    return NextResponse.json(rule)
  }catch(e:any){
    if(e.code==="P2002") return NextResponse.json({error:"Pravilo već postoji"}, {status:400})
    throw e
  }
}
