"use client";
import { QrCode, ChefHat, Smartphone, Euro, Sparkles, Check, Menu, X, UtensilsCrossed, LayoutGrid, BarChart3, Zap, ArrowRight } from "lucide-react";
import { useState } from "react";

export default function Page() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return (
    <div className="min-h-screen bg-[#FFFBF7] text-zinc-900 antialiased">
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap');*{font-family:Inter,sans-serif} html{scroll-behavior:smooth; scroll-padding-top:80px}`}</style>

      <header className="sticky top-0 z-50 border-b bg-[#FFFEFB]/90 backdrop-blur-xl">
        <div className="mx-auto max-w- h- px-5 lg:px-6 flex items-center justify-between">
          <a href="/" className="flex items-center gap-3"><div className="h-9 w-9 rounded-full bg-gradient-to-br from-emerald-400 to-teal-600" /><span className="font-extrabold">TableBoost<span className="text-zinc-400">.app</span></span></a>
          <nav className="hidden lg:flex gap-8 text- font-medium">
            <a href="#kako-radi" className="hover:text-zinc-900 text-zinc-600 hover:underline underline-offset-8 decoration-2">Kako radi</a>
            <a href="#zarada" className="hover:text-zinc-900 text-zinc-600 hover:underline underline-offset-8 decoration-2">Zarada</a>
            <a href="#funkcionalnosti" className="hover:text-zinc-900 text-zinc-600 hover:underline underline-offset-8 decoration-2">Funkcionalnosti</a>
            <a href="#uloge" className="hover:text-zinc-900 text-zinc-600 hover:underline underline-offset-8 decoration-2">Uloge</a>
          </nav>
          <div className="hidden lg:flex gap-3"><a href="/login" className="h-10 px-5 rounded-full bg-zinc-900 text-white text- font-semibold grid place-items-center">Prijava</a><a href="/login" className="h-10 px-5 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 text-white text- font-bold grid place-items-center">Pokreni besplatno</a></div>
          <button onClick={()=>setMobileOpen(!mobileOpen)} className="lg:hidden h-10 w-10 rounded-full bg-zinc-900 text-white grid place-items-center">{mobileOpen?<X size={18}/>:<Menu size={18}/>}</button>
        </div>
        {mobileOpen && (
          <div className="lg:hidden border-t bg-white px-5 py-5 space-y-2">
            <a onClick={()=>setMobileOpen(false)} href="#kako-radi" className="block h-12 px-4 rounded-2xl bg-zinc-100 grid items-center font-medium">Kako radi</a>
            <a onClick={()=>setMobileOpen(false)} href="#zarada" className="block h-12 px-4 rounded-2xl bg-zinc-100 grid items-center font-medium">Zarada</a>
            <a onClick={()=>setMobileOpen(false)} href="#funkcionalnosti" className="block h-12 px-4 rounded-2xl bg-zinc-100 grid items-center font-medium">Funkcionalnosti</a>
            <a onClick={()=>setMobileOpen(false)} href="#uloge" className="block h-12 px-4 rounded-2xl bg-zinc-100 grid items-center font-medium">Uloge</a>
            <div className="pt-2 grid grid-cols-2 gap-3"><a href="/login" className="h-12 rounded-full bg-zinc-900 text-white grid place-items-center font-semibold">Prijava</a><a href="/login" className="h-12 rounded-full bg-emerald-600 text-white grid place-items-center font-bold">Pokreni</a></div>
          </div>
        )}
      </header>

      <section className="mx-auto max-w- px-5 lg:px-6 pt-16 pb-10 text-center">
        <div className="inline-flex px-3 py-1 rounded-full border bg-white text- font-semibold">Novo • KDS v2 LIVE</div>
        <h1 className="mt-6 text- lg:text- font-black leading-[0.95]">Restoran koji<br/>radi <span className="bg-gradient-to-br from-emerald-500 to-teal-600 bg-clip-text text-transparent">brže.</span></h1>
        <p className="mt-4 text-zinc-600 max-w-2xl mx-auto">QR jelovnik + KDS kuhinja + konobar app. Postavka 15 minuta.</p>
      </section>

      <section id="kako-radi" className="bg-white border-y scroll-mt-"><div className="mx-auto max-w- px-5 lg:px-6 py-20"><div className="inline-flex px-3 py-1 rounded-full bg-zinc-900 text-white text- font-bold">KAKO RADI</div><h2 className="mt-4 text- lg:text- font-extrabold">Od QR-a do kuhinje u 3 koraka</h2><div className="mt-10 grid lg:grid-cols-3 gap-6"><div className="rounded- border bg-amber-50 p-7"><div className="h-12 w-12 rounded-2xl bg-amber-500 grid place-items-center text-white"><QrCode/></div><h3 className="mt-4 font-bold text-">01 Gost skenira</h3><p className="text-sm text-zinc-600 mt-2">QR otvara jelovnik, naručuje sam bez čekanja konobara.</p></div><div className="rounded- border bg-emerald-50 p-7"><div className="h-12 w-12 rounded-2xl bg-emerald-500 grid place-items-center text-white"><ChefHat/></div><h3 className="mt-4 font-bold text-">02 Kuhinja kuha</h3><p className="text-sm text-zinc-600 mt-2">KDS ekran LIVE 3s, boje prioriteta, timer, zvuk za novo.</p></div><div className="rounded- border bg-violet-50 p-7"><div className="h-12 w-12 rounded-2xl bg-violet-500 grid place-items-center text-white"><Smartphone/></div><h3 className="mt-4 font-bold text-">03 Konobar poslužuje</h3><p className="text-sm text-zinc-600 mt-2">Push obavijest kad je gotovo, naplata na jedan tap.</p></div></div></div></section>

      <section id="zarada" className="bg-[#FFFBF7] border-b scroll-mt-"><div className="mx-auto max-w- px-5 lg:px-6 py-20"><div className="inline-flex gap-2 px-3 py-1 rounded-full bg-amber-100 text-amber-800 text- font-bold border"><Euro size={14}/> NE SAMO BRŽE, NEGO I PROFITABILNIJE</div><h2 className="mt-4 text- lg:text- font-extrabold max-w-3xl">Kako ti dižemo promet bez dodatnog osoblja</h2><div className="mt-10 grid lg:grid-cols-3 gap-5 max-w-5xl"><div className="rounded- bg-gradient-to-br from-emerald-500 to-teal-600 p-6 text-white"><div className="text- font-black">+27%</div><div className="text-sm">Prosječan račun - QR uvijek ponudi dodatak</div></div><div className="rounded- bg-zinc-900 p-6 text-white"><div className="text- font-black">-80%</div><div className="text-sm text-zinc-400">Manje grešaka, direkt u KDS</div></div><div className="rounded- bg-white border p-6"><div className="text- font-black">2x</div><div className="text-sm text-zinc-600">Brži obrt stola, naplata na tap</div></div></div></div></section>

      <section id="funkcionalnosti" className="mx-auto max-w- px-5 lg:px-6 py-20 scroll-mt-"><div className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 shadow ring-1 ring-zinc-200"><Sparkles size={14} className="text-amber-500"/><span className="text- font-bold tracking-widest">FUNKCIJE</span></div><h2 className="mt-4 text- font-extrabold lg:text-">Sve što ti treba, ništa što ne treba.</h2><div className="mt-12 grid sm:grid-cols-2 lg:grid-cols-3 gap-5"><div className="rounded- border bg-white p-6 shadow-sm"><div className="h-11 w-11 rounded-2xl bg-amber-500 grid place-items-center text-white"><QrCode size={20}/></div><h3 className="mt-4 font-bold">QR jelovnik</h3><p className="text-sm text-zinc-600 mt-1">5 jezika, fotke, alergeni, cijene uživo.</p></div><div className="rounded- border bg-white p-6 shadow-sm"><div className="h-11 w-11 rounded-2xl bg-emerald-500 grid place-items-center text-white"><ChefHat size={20}/></div><h3 className="mt-4 font-bold">KDS kuhinja</h3><p className="text-sm text-zinc-600 mt-1">LIVE 3s, boje, timer, zvuk.</p></div><div className="rounded- border bg-white p-6 shadow-sm"><div className="h-11 w-11 rounded-2xl bg-violet-500 grid place-items-center text-white"><Smartphone size={20}/></div><h3 className="mt-4 font-bold">Konobar app</h3><p className="text-sm text-zinc-600 mt-1">Push gotovo, stolovi, naplata.</p></div><div className="rounded- border bg-white p-6 shadow-sm"><div className="h-11 w-11 rounded-2xl bg-blue-500 grid place-items-center text-white"><LayoutGrid size={20}/></div><h3 className="mt-4 font-bold">Upravljanje stolovima</h3><p className="text-sm text-zinc-600 mt-1">Raspored, rezervacije, spajanje.</p></div><div className="rounded- border bg-white p-6 shadow-sm"><div className="h-11 w-11 rounded-2xl bg-orange-500 grid place-items-center text-white"><BarChart3 size={20}/></div><h3 className="mt-4 font-bold">Izvještaji</h3><p className="text-sm text-zinc-600 mt-1">Promet, najprodavanije, marže.</p></div><div className="rounded- border bg-white p-6 shadow-sm"><div className="h-11 w-11 rounded-2xl bg-teal-500 grid place-items-center text-white"><Zap size={20}/></div><h3 className="mt-4 font-bold">Postavka 15 min</h3><p className="text-sm text-zinc-600 mt-1">Uneseš jelovnik, isprintaš QR.</p></div></div></section>

      <section id="uloge" className="bg-white border-t scroll-mt-"><div className="mx-auto max-w- px-5 lg:px-6 py-20"><h2 className="text- font-extrabold text-center lg:text-">Svatko vidi ono što mu treba</h2><div className="mt-10 grid lg:grid-cols-3 gap-6"><div className="rounded- border overflow-hidden"><div className="bg-gradient-to-br from-emerald-500 to-teal-600 p-6 text-white font-bold">ADMIN - Vlasnik</div><div className="p-6 space-y-2 text-sm"><div className="flex gap-2"><Check size={16} className="text-emerald-600"/> Uredi jelovnik za 10s</div><div className="flex gap-2"><Check size={16} className="text-emerald-600"/> Vidi promet uživo</div><div className="flex gap-2"><Check size={16} className="text-emerald-600"/> Upravljaj osobljem</div></div></div><div className="rounded- border overflow-hidden"><div className="bg-gradient-to-br from-amber-400 to-orange-500 p-6 text-white font-bold">KONOBAR</div><div className="p-6 space-y-2 text-sm"><div className="flex gap-2"><Check size={16} className="text-amber-600"/> Push kad je gotovo</div><div className="flex gap-2"><Check size={16} className="text-amber-600"/> Naplata na tap</div><div className="flex gap-2"><Check size={16} className="text-amber-600"/> Status stolova</div></div></div><div className="rounded- border overflow-hidden"><div className="bg-gradient-to-br from-violet-600 to-blue-500 p-6 text-white font-bold">KUHINJA</div><div className="p-6 space-y-2 text-sm"><div className="flex gap-2"><Check size={16} className="text-violet-600"/> Timer za svako jelo</div><div className="flex gap-2"><Check size={16} className="text-violet-600"/> Boje prioriteta</div><div className="flex gap-2"><Check size={16} className="text-violet-600"/> Zvuk za novo</div></div></div></div></div></section>

      <section className="bg-gradient-to-br from-emerald-600 to-violet-600 py-16 text-center text-white"><h2 className="text- font-extrabold">Spreman? Idemo postaviti tvoj restoran.</h2><a href="/login" className="mt-6 inline-flex px-7 py-3.5 rounded-full bg-white text-zinc-900 font-bold">Idi na login →</a></section>
      <footer className="h- border-t flex items-center justify-between px-5 lg:px-6 text- text-zinc-500"><span>TableBoost.app © {new Date().getFullYear()}</span><a href="/login" className="font-bold text-zinc-800">Prijava →</a></footer>
    </div>
  );
}
