"use client";
import { useState } from "react";
import { QrCode, ChefHat, BellRing, CreditCard, Sparkles, Plus, Timer, Check, X, Smartphone, LayoutDashboard, BarChart3, Clock3, Users, ShieldCheck, UtensilsCrossed, Zap, ArrowRight, Menu, TrendingUp, Euro, Receipt } from "lucide-react";
export default function Page() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return (
    <div className="min-h-screen bg-[#FFFEFB] text-zinc-900 antialiased">
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap');*{font-family:Inter,sans-serif}`}</style>
      <header className="sticky top-0 z-50 backdrop-blur-xl bg-white/80 border-b border-zinc-100">
        <div className="mx-auto max-w-[1280px] px-5 lg:px-8 h-[68px] flex items-center justify-between">
          <a href="/" className="flex items-center gap-2.5"><div className="h-8 w-8 rounded-full bg-gradient-to-br from-emerald-400 to-teal-600"/><span className="font-extrabold">TableBoost<span className="text-zinc-400">.app</span></span></a>
          <nav className="hidden lg:flex gap-8 text-[14px] font-medium text-zinc-600"><a href="#kako-radi">Kako radi</a><a href="#zarada">Zarada</a><a href="#funkcionalnosti">Funkcionalnosti</a><a href="#uloge">Uloge</a></nav>
          <div className="hidden lg:flex gap-3"><a href="/login" className="px-4 py-2 rounded-full bg-zinc-900 text-white text-[14px] font-semibold">Prijava</a><a href="/login" className="px-5 py-2.5 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 text-white text-[14px] font-bold">Pokreni besplatno</a></div>
          <button onClick={()=>setMobileOpen(v=>!v)} className="lg:hidden p-2 rounded-xl bg-zinc-900 text-white">{mobileOpen?<X size={18}/>:<Menu size={18}/>}</button>
        </div>
        {mobileOpen && <div className="lg:hidden border-t bg-white px-5 py-5"><a href="#zarada" className="block py-2">Zarada</a><a href="/login" className="block mt-3 text-center py-3 rounded-full bg-zinc-900 text-white">Prijava</a></div>}
      </header>
      <section className="relative overflow-hidden">
        <div className="pointer-events-none absolute inset-0"><div className="absolute -top-24 -left-24 h-[520px] w-[520px] rounded-full bg-emerald-200/40 blur-[90px]"/><div className="absolute -top-10 right-[-80px] h-[460px] w-[460px] rounded-full bg-amber-200/50 blur-[80px]"/></div>
        <div className="relative mx-auto max-w-[1280px] px-5 lg:px-8 pt-14 lg:pt-24 pb-12">
          <div className="mx-auto max-w-3xl text-center">
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white border text-[12px] font-semibold"><span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse"/>Novo • KDS v2 LIVE</div>
            <h1 className="mt-6 text-[40px] lg:text-[72px] font-[900] leading-[0.95] tracking-tight">Restoran koji<br/>radi <span className="bg-gradient-to-br from-emerald-500 to-teal-600 bg-clip-text text-transparent">brže.</span></h1>
            <p className="mt-5 text-[16px] lg:text-[18px] text-zinc-600 max-w-2xl mx-auto">QR jelovnik + KDS kuhinja + konobar app. Gosti naručuju sami, kuhinja vidi sve LIVE.</p>
            <div className="mt-7 flex flex-col sm:flex-row gap-3 justify-center"><a href="/login" className="px-7 py-3.5 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 text-white font-bold inline-flex items-center justify-center gap-2">Pokreni besplatno <ArrowRight size={18}/></a><a href="#zarada" className="px-7 py-3.5 rounded-full bg-white border font-semibold">Kako zarađuješ više?</a></div>
          </div>
        </div>
      </section>
      <section id="zarada" className="bg-[#FFFBF7] border-y border-zinc-100"><div className="mx-auto max-w-[1280px] px-5 lg:px-8 py-16 lg:py-24">
        <div className="max-w-3xl"><div className="inline-flex gap-2 px-3 py-1 rounded-full bg-amber-100 text-amber-800 text-[11px] font-bold border"><Euro size={14}/> NE SAMO BRŽE, NEGO I PROFITABILNIJE</div><h2 className="mt-4 text-[32px] lg:text-[48px] font-extrabold leading-[1.05]">Kako ti dižemo promet bez dodatnog osoblja</h2><p className="mt-3 text-zinc-600">QR je tvoj najbolji prodavač - nikad ne zaboravi pitati "Želite li dodatak?"</p></div>
        <div className="mt-10 grid lg:grid-cols-3 gap-5 max-w-5xl"><div className="rounded-[24px] bg-gradient-to-br from-emerald-500 to-teal-600 p-6 text-white"><div className="flex justify-between"><TrendingUp size={20}/><span className="text-[11px] bg-white/20 px-2.5 py-1 rounded-full">PROSJEČAN RAČUN</span></div><div className="mt-6 text-[40px] font-black">+27%</div><div className="mt-2 text-[13px] text-emerald-50">QR predlaže dodatke, deserte i pića u pravom trenutku.</div></div><div className="rounded-[24px] bg-zinc-900 p-6 text-white"><div className="flex justify-between"><ShieldCheck size={20}/><span className="text-[11px] bg-white/10 px-2.5 py-1 rounded-full">GREŠKE</span></div><div className="mt-6 text-[40px] font-black">-80%</div><div className="mt-2 text-[13px] text-zinc-400">Manje krivo zapisanih narudžbi. Sve ide direkt u KDS.</div></div><div className="rounded-[24px] bg-white border p-6"><div className="flex justify-between"><Clock3 size={20}/><span className="text-[11px] bg-zinc-100 px-2.5 py-1 rounded-full">OBRT STOLA</span></div><div className="mt-6 text-[40px] font-black">2x</div><div className="mt-2 text-[13px] text-zinc-600">Brži obrt jer gosti naručuju dok čekaju, naplata na tap.</div></div></div>
        <div className="mt-12 grid lg:grid-cols-3 gap-6 max-w-6xl"><div className="rounded-[28px] bg-gradient-to-br from-amber-50 to-orange-50 border border-amber-200 p-6"><div className="h-12 w-12 rounded-2xl bg-white border flex items-center justify-center"><Plus size={20} className="text-amber-600"/></div><div className="mt-4 font-bold text-[18px]">Pametni prijedlozi koji prodaju</div><div className="mt-2 text-[13px]">Kad gost odabere burger, QR pita:<br/><span className="inline-flex mt-2 bg-white border rounded-full px-3 py-1 text-[12px] font-semibold">Dodaj pomfrit? +2,50€</span><br/><span className="inline-flex mt-1.5 bg-white border rounded-full px-3 py-1 text-[12px]">Desert uz kavu? +1,90€</span></div><div className="mt-4 text-[12px] bg-white/70 border border-amber-200 rounded-xl p-3">Konobar ponekad zaboravi. QR nikad. To je +18-30% na svaki račun.</div></div><div className="rounded-[28px] bg-emerald-50 border border-emerald-200 p-6"><div className="h-12 w-12 rounded-2xl bg-white border flex items-center justify-center"><Zap size={20} className="text-emerald-600"/></div><div className="mt-4 font-bold text-[18px]">Manje praznog hoda</div><div className="mt-2 text-[13px] leading-6">• Ne trči 30x do kuhinje<br/>• Timer smanjuje čekanje<br/>• Dok čeka glavno, naruči piće preko QR-a<br/>• Naplata na tap</div></div><div className="rounded-[28px] bg-violet-50 border border-violet-200 p-6"><div className="h-12 w-12 rounded-2xl bg-white border flex items-center justify-center"><BarChart3 size={20} className="text-violet-600"/></div><div className="mt-4 font-bold text-[18px]">Zadovoljan gost se vraća</div><div className="mt-2 text-[13px] leading-6">• Točna narudžba<br/>• Brza usluga<br/>• Lako plaćanje - podjela računa<br/>• Recenzija dok je za stolom</div></div></div>
      </div></section>
      <section className="mx-auto max-w-[1280px] px-5 lg:px-8 py-16 text-center"><h2 className="text-[32px] font-extrabold">Spreman? Idemo postaviti tvoj restoran.</h2><a href="/login" className="mt-6 inline-flex px-7 py-3.5 rounded-full bg-zinc-900 text-white font-bold">Idi na login →</a></section>
      <footer className="border-t"><div className="mx-auto max-w-[1280px] px-5 lg:px-8 h-[72px] flex items-center justify-between text-[13px] text-zinc-500"><div className="flex items-center gap-2"><div className="h-5 w-5 rounded-full bg-gradient-to-br from-emerald-400 to-teal-600"/><span className="font-bold text-zinc-800">TableBoost.app</span></div><a href="/login" className="font-semibold text-zinc-800">Prijava →</a></div></footer>
    </div>
  );
}
