"use client"
import { useEffect, useState } from "react"
type Cat = { id:string, name:string, nameEn?:string|null, nameDe?:string|null, order:number, _count?:{items:number} }
export default function CategoriesPage(){
  const [cats,setCats]=useState<Cat[]>([]); const [newName,setNewName]=useState(""); const [saving,setSaving]=useState<string|null>(null)
  const load=async()=>{ const r=await fetch("/api/admin/categories"); const d=await r.json(); setCats(d.categories||[]) }
  useEffect(()=>{load()},[])
  const add=async()=>{ if(!newName.trim()) return; setSaving("new"); try { const r=await fetch("/api/admin/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:newName})}); const j=await r.json(); if(r.ok){ setNewName(""); setCats([...cats,j]) } else alert(j.error) } catch(e:any){ alert(e.message) } setSaving(null) }
  const save=async(c:Cat)=>{ setSaving(c.id); await fetch(`/api/admin/categories/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:c.name,nameEn:c.nameEn,nameDe:c.nameDe,order:c.order})}); setSaving(null) }
  const del=async(id:string)=>{ if(!confirm("Obrisati kategoriju?")) return; const r=await fetch(`/api/admin/categories/${id}`,{method:"DELETE"}); const j=await r.json(); if(!r.ok) alert(j.error); else setCats(p=>p.filter(x=>x.id!==id)) }
  const move=async(id:string, dir: -1|1)=>{ const idx=cats.findIndex(x=>x.id===id); const newIdx=idx+dir; if(newIdx<0||newIdx>=cats.length) return; const newCats=[...cats]; const [moved]=newCats.splice(idx,1); newCats.splice(newIdx,0,moved); const withOrder=newCats.map((c,i)=>({...c,order:i})); setCats(withOrder); await Promise.all(withOrder.map(c=>fetch(`/api/admin/categories/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({order:c.order})}))) }
  return(<div className="p-4 max-w-4xl mx-auto"><div className="flex justify-between items-end mb-3"><div><h1 className="text-lg font-bold leading-tight">Kategorije</h1><p className="text- text-neutral-500">{cats.length} kategorija • redoslijed = prikaz gostu</p></div></div><div className="flex gap-2 mb-4"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Nova npr. Meso" className="border rounded-full px-3 h-8 text-xs flex-1" onKeyDown={e=>e.key==="Enter"&&add()}/><button onClick={add} disabled={saving==="new"} className="bg-black text-white px-4 h-8 rounded-full text-xs">{saving==="new"?"...":"Dodaj"}</button></div><div className="bg-white border rounded-xl overflow-hidden"><div className="grid grid-cols-12 gap-2 px-3 py-2 bg-zinc-50 text- font-bold uppercase tracking-wider text-neutral-500 border-b"><div className="col-span-1"></div><div className="col-span-3">HR</div><div className="col-span-3">EN</div><div className="col-span-3">DE</div><div className="col-span-2 text-right">Akcija</div></div><div className="divide-y divide-black/[0.04]">{cats.map(c=>(<div key={c.id} className="grid grid-cols-12 gap-2 px-3 py-2 items-center hover:bg-zinc-50"><div className="col-span-1 flex gap-1"><button onClick={()=>move(c.id,-1)} className="border w-6 h-6 rounded text-">↑</button><button onClick={()=>move(c.id,1)} className="border w-6 h-6 rounded text-">↓</button></div><div className="col-span-3"><input value={c.name} onChange={e=>setCats(p=>p.map(x=>x.id===c.id?{...x,name:e.target.value}:x))} className="w-full border rounded-lg px-2 h-7 text-xs font-medium"/><div className="text- text-neutral-400 mt-0.5">{c._count?.items??0} artikala</div></div><div className="col-span-3"><input value={c.nameEn||""} onChange={e=>setCats(p=>p.map(x=>x.id===c.id?{...x,nameEn:e.target.value}:x))} placeholder="EN" className="w-full border border-blue-100 rounded-lg px-2 h-7 text-xs"/></div><div className="col-span-3"><input value={c.nameDe||""} onChange={e=>setCats(p=>p.map(x=>x.id===c.id?{...x,nameDe:e.target.value}:x))} placeholder="DE" className="w-full border border-red-100 rounded-lg px-2 h-7 text-xs"/></div><div className="col-span-2 flex gap-1 justify-end"><button onClick={()=>save(c)} disabled={saving===c.id} className="bg-black text-white px-2.5 h-7 rounded-full text-">{saving===c.id?"...":"Spremi"}</button><button onClick={()=>del(c.id)} className="text-red-600 border px-2 h-7 rounded-full text-">X</button></div></div>))}</div></div></div>)
}
